### ISSUE TITLE
default install with sample data fails

### ISSUE THREAD

**Issue by litody** [redbaron76/PongoCMS-Laravel-cms-bundle#13]
table elements_pages is created and attempt to load sample data is made.  Column order_id gets defined as INT not NULL.  But sample data contains empty text string for that column and causes insert to fail.
My local MySQL (5.5.16) server may do more rigid tests than other setups but sample data should not cause fail

**Comment by redbaron76** [comment]
Check last release of PongoCMS.
Try a fresh installation and all should work correctly.

**Comment by litody** [comment]
thanks, install load of data works now.
