### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by def-media** [redbaron76/PongoCMS-Laravel-cms-bundle#2]
I test Pongo CMS and I noticed a problem with adding new users. Actually, I added a two new users with Editor and Manager role with no problem, but when I try to login with new Editor user, the "Login error!" arises. 
When I try to login with a Manager role user, Firefox gives me "The page isn't redirecting properly".
Have you noticed any similar problem or perhaps problem occurs only on my side?
I'm testing on local machine, Ubuntu 12.04, Apache 2.2.22, PHP 5.3.10-1ubuntu3.2, MySQL 5.5.24-0ubuntu0.12.04.1.

**Comment by redbaron76** [comment]
Sorry about that.
Now issue has been fixed.

Just re-install and re-setup the bundle

**Comment by def-media** [comment]
Thank You, very much!
