### ISSUE TITLE
The admin loads but the home page and subsequent pages dont load

### ISSUE THREAD

**Issue by nomad23** [redbaron76/PongoCMS-Laravel-cms-bundle#22]
im getting this error after a fresh install of pongo 

/home/derick/Documents/example/genunlock/bundles/cms/libraries/cmsutility.php on line 159
this is after using artisan install method

**Comment by redbaron76** [comment]
'url' => '',

in /application/config/application.php must be set.

Il giorno 19/feb/2013, alle ore 11:23, nomad23 notifications@github.com ha scritto:

**Comment by nomad23** [comment]
Thanks... That helped!!!
