### ISSUE TITLE
Menu don't appear unless it's called "nav"

### ISSUE THREAD

**Issue by rollbackpt** [redbaron76/PongoCMS-Laravel-cms-bundle#24]
In Services->Menu i created a new menu. It allows me to choose the name for the menu and i called it "menu" but it didn't show up so i changed it to "nav" as it is called in the defaut theme and it worked. Is this a bug or i am doing something wrong?

**Comment by redbaron76** [comment]
You can create a menu with name "whatever" and then call it using a menu marker [$MENU["name":"whatever"]]

Il giorno 03/mar/2013, alle ore 14:06, João Ribeiro notifications@github.com ha scritto:

**Comment by rollbackpt** [comment]
Thanks i already notice that yesterday and i forgot to close the issue.
