### ISSUE TITLE
Problem with add images to galleries, banners etc.

### ISSUE THREAD

**Issue by partikus** [redbaron76/PongoCMS-Laravel-cms-bundle#26]
Hi, 
I've just installed pongo cms. I'm researching and learning pongo now, but I can't find possibility add images to gallery. 

Could you tell me how can I do it? The best please solution will be if give me instruction step by step what I have to do. 

Thanks

**Comment by redbaron76** [comment]
1) Add media into "Media" tab on each Page/Element section.
2) Create a new gallery and give it a name into Services->Gallery
3) Go to Services->Media and add the media to the new created Gallery
4) Use Marker $GALLERY into your text

Il giorno 16/mar/2013, alle ore 21:05, Michał notifications@github.com ha scritto:

**Comment by partikus** [comment]
It's not comfortable. I think that user should have possibility add media
to gallery when create new gallery. Good solution will be popup which give
this possibility. What do you think about it?

In free time, I'm going to try create this feature.

2013/3/17 redbaron76 notifications@github.com

> 1) Add media into "Media" tab on each Page/Element section.
> 2) Create a new gallery and give it a name into Services->Gallery
> 3) Go to Services->Media and add the media to the new created Gallery
> 4) Use Marker $GALLERY into your text
> 
> Il giorno 16/mar/2013, alle ore 21:05, Micha³ notifications@github.com
> ha scritto:
> 
> > Hi,
> > I've just installed pongo cms. I'm researching and learning pongo now,
> > but I can't find possibility add images to gallery.
> > 
> > Could you tell me how can I do it? The best please solution will be if
> > give me instruction step by step what I have to do.
> > 
> > Thanks
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/redbaron76/PongoCMS-Laravel-cms-bundle/issues/26#issuecomment-15020803
> .

## 

Micha Szczur
www.twojwodzirej.pl

**Comment by redbaron76** [comment]
Well, previous version had the feature you suggested but it was not so comfortable too in case of a large number of images to display.
I think it's better to create your gallery and then add it to text through $GALLERY marker.
Then, just link to gallery images you need.

Inviato da iPad

Il giorno 17/mar/2013, alle ore 12:33, Michał notifications@github.com ha scritto:

**Comment by partikus** [comment]
Ok, but in my opinion, when user want add e.g 40 images, solution which provide pongo isn't friendly. Ability add new photos to gallery should be more useful.

What I mean?
Now user must singly add image to gallery. It's uncomfortable and very slow.

Maybe better solution will be popup in which user will see two columns. And if he want add photo to gallery he have to drag image from left column to right column.
