### ISSUE TITLE
Google analytics stopped working when deployed on vps

### ISSUE THREAD

**Issue by Edwin-Luijten** [redbaron76/PongoCMS-Laravel-cms-bundle#5]
Google analytics stopped working when deployed on vps (it worked on local machine and no information has been changed):

Unhandled Exception
Message:

GAPI: Failed to authenticate user. Error: "Request failed, fopen provides no further information"

Location:

D:\www_Staging\le-feu\bundles\cms\libraries\gapi.php on line 418

**Comment by redbaron76** [comment]
That sounds strange. There is no relation between gapi library (php) and Analytics plugin (js).
Did you set analytics account parameters correctly in 'settings.php'?

**Comment by Edwin-Luijten** [comment]
I double checked the account parameters they are both the same.

**Comment by Edwin-Luijten** [comment]
After further investigating, i have a 64bit server and it seems the curl module is not compatible and is not loaded. so it uses fopen instead (maybe there goes something wrong while using fopen).

I'm going to correct these problems with my sever installation, and hope it solves the problem.

**Comment by Edwin-Luijten** [comment]
It was indeed an incorrect version of the curl extension :). Problem is fixed.
Link to correct version of 64bit curl extension: http://www.anindya.com/php-5-4-3-and-php-5-3-13-x64-64-bit-for-windows/
